filebeat.inputs:
- type: log
  paths:
    - /var/lib/docker/containers/*/*.log
  processors:
  - add_docker_metadata: ~
  - drop_event:
      when:
        or:
          - regexp:
              docker.container.name: 'filebeat'
          - regexp:
              docker.container.name: 'kafka'
          - regexp:
              docker.container.name: 'zookeeper'
          - regexp:
              docker.container.name: 'gateway'
          - regexp:
              docker.container.name: 'redis'
          - regexp:
              docker.container.name: 'mongo'
  - drop_fields:
      fields: ["host", "source", "offset", "log", "prospector", "input", "beat"]

output.kafka:
  hosts: ["kafka:9092"]
  topic: 'totoLogs'
  partition.round_robin:
    reachable_only: false

  required_acks: 1
  compression: gzip
  max_message_bytes: 100000000
